branches:
  - main
preset: angular
tagFormat: ${version}

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - - "@semantic-release/exec"
    - message: |
        chore(release): ${nextRelease.version} \n\n${nextRelease.notes}
